Provide install targets
dschmidt/libcrashreporter-qt pull request #36
Opened 2023-02-09 13:09 UTC by TheOneRing

2023-02-09 13:09 UTC, TheOneRing commented
@dschmidt @fmoc

2023-02-09 21:10 UTC, dschmidt commented
Hm this probably also installs stuff when used as a submodule, right? 😏

2023-02-10 08:22 UTC, TheOneRing commented
Hmm

> Hm this probably also installs stuff when used as a submodule, right? 😏

I think thats what exclude_from_all is for.
(Set in ownCloud)
https://cmake.org/cmake/help/latest/command/add_subdirectory.html

2023-02-10 13:40 UTC, fmoc commented
`EXCLUDE_FROM_ALL` prevents targets from being pulled into the equivalent of `make all`. As long as targets are not referenced, they should not be installed. If you `target_link_libraries`, though, I think they will be `make install`ed.

2023-02-14 12:59 UTC, TheOneRing commented
To be extra sure I tested it, and its indeed excluded.

2023-02-14 13:45 UTC, fmoc requested changes

2023-02-14 13:45 UTC, fmoc commented on src/libcrashreporter-gui/CMakeLists.txt
> +install(FILES CrashReporter.h DESTINATION ${INCLUDE_INSTALL_DIR}/CrashReporterQt/libcrashreporter-gui)
You may want to use `PUBLIC_HEADER` instead. That way you can add the header to the right target.

2023-02-14 13:45 UTC, fmoc commented on src/libcrashreporter-handler/CMakeLists.txt
> +install(FILES Handler.h DESTINATION ${INCLUDE_INSTALL_DIR}/CrashReporterQt/libcrashreporter-handler)
You may want to use `PUBLIC_HEADER` instead. That way you can add the header to the right target.

2023-02-15 11:43 UTC, fmoc commented on src/libcrashreporter-gui/CMakeLists.txt
> +install(FILES CrashReporter.h DESTINATION ${INCLUDE_INSTALL_DIR}/CrashReporterQt/libcrashreporter-gui)
What's your concern? I've used `PUBLIC_HEADER` before to install public headers (on non-mac platforms, typically).

2023-02-21 10:02 UTC, fmoc approved these changes

2023-02-21 10:02 UTC, merged